name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.config.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Windows VS2019, os: windows-latest }
          - { name: Linux GCC, os: ubuntu-latest }
          - {
              name: Linux Clang,
              os: ubuntu-latest,
              flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++,
            }
          - { name: MacOS XCode, os: macos-latest }

    steps:
      - name: Workshop - Checkout Code
        uses: actions/checkout@v2

      - name: SFML - Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libudev-dev libgl1-mesa-dev libegl1-mesa-dev libopenal-dev libvorbis-dev libflac-dev

      - name: SFML - Checkout Code
        uses: actions/checkout@v2
        with:
          repository: SFML/SFML
          path: SFML

      - name: SFML - Configure CMake
        shell: bash
        run: cmake -S $GITHUB_WORKSPACE/SFML -B $GITHUB_WORKSPACE/SFML/build -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/SFML/install -DSFML_BUILD_NETWORK=OFF -DBUILD_SHARED_LIBS=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON ${{matrix.platform.flags}}

      - name: SFML - Build
        shell: bash
        run: cmake --build $GITHUB_WORKSPACE/SFML/build --config Release --target install

      - name: Workshop - Configure CMake
        shell: bash
        run: cmake -S $GITHUB_WORKSPACE -B $GITHUB_WORKSPACE/build -DSFML_DIR=$GITHUB_WORKSPACE/SFML/install/lib/cmake/SFML -DCMAKE_VERBOSE_MAKEFILE=ON  ${{matrix.platform.flags}}

      - name: Workshop - Build
        shell: bash
        run: cmake --build $GITHUB_WORKSPACE/build --config Release
